# Generated by Django 3.2.23 on 2023-12-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('likeCount', models.IntegerField(blank=True)),
                ('viewCount', models.IntegerField(blank=True)),
                ('contents', models.TextField()),
            ],
        ),
    ]
