# Generated by Django 3.2.23 on 2023-12-15 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='likeCount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='viewCount',
            field=models.IntegerField(),
        ),
    ]
