# Generated by Django 3.2.23 on 2023-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231215_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='contents',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='likeCount',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='viewCount',
            field=models.IntegerField(blank=True),
        ),
    ]
