# Generated by Django 3.2.23 on 2023-12-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='bb/%Y/%m/%d/1044'),
        ),
    ]
